export const PROPERTY_TYPES = ['Room', 'Flat', 'Hostel', 'PG']

export const AMENITIES = [
  { id: 'wifi', label: 'WiFi' },
  { id: 'ac', label: 'AC' },
  { id: 'food', label: 'Food' },
  { id: 'parking', label: 'Parking' },
  { id: 'laundry', label: 'Laundry' },
  { id: 'gym', label: 'Gym' },
  { id: 'security', label: 'Security' },
  { id: 'cctv', label: 'CCTV' },
  { id: 'power', label: 'Backup Power' },
  { id: 'water', label: '24h Water' },
]

export const FURNISHING_TYPES = ['full', 'semi', 'none']

export const CITIES = [
  'Dehradun', 'Srinagar', 'Rishikesh', 'Haldwani', 'Nainital', 'Haridwar', 'Roorkee', 'Rudrapur', 'Pune', 'Delhi'
]

export const SORT_OPTIONS = [
  { value: 'created_at:desc', label: 'Newest First' },
  { value: 'created_at:asc', label: 'Oldest First' },
  { value: 'price:asc', label: 'Price: Low to High' },
  { value: 'price:desc', label: 'Price: High to Low' },
  { value: 'views:desc', label: 'Most Popular' },
]

export const MOCK_PROPERTIES = [
  {
    id: 'e2fa5154-1506-4b47-9dc4-142f1f582d9f',
    title: 'Premium Studio near IT Park',
    description: 'A beautifully furnished studio apartment perfect for working professionals. Fully equipped kitchen, high-speed WiFi, 24/7 security.',
    price: 18000,
    city: 'Dehradun',
    area: 'Rajpur Road',
    pincode: '248001',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'parking', 'security', 'cctv'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'full',
    pet_friendly: false,
    balcony: true,
    landlord_verified: true,
    nearby_landmarks: 'Near Pacific Mall, 2km from Clock Tower',
    views: 342,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    landlord: { name: 'Rajesh Negi', phone: '+91 98765 43210', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh' },
    created_at: '2026-01-15',
  },
  {
    id: 'f3eb6265-2617-5c58-0ed5-253f2f693e0g',
    title: 'Cozy PG for Students',
    description: 'Fully furnished PG accommodation with home-cooked meals included. Walk to university campus.',
    price: 8500,
    city: 'Srinagar',
    area: 'Main Market',
    pincode: '246174',
    type: 'PG',
    amenities: ['wifi', 'food', 'laundry', 'security'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'full',
    pet_friendly: false,
    balcony: false,
    landlord_verified: true,
    nearby_landmarks: 'HNBGU Campus 500m, Srinagar Market 1km',
    views: 218,
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    landlord: { name: 'Priya Rawat', phone: '+91 87654 32109', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya' },
    created_at: '2026-01-20',
  },
  {
    id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    title: 'Modern 1BHK in Rishikesh',
    description: 'Stylish 1BHK apartment with mountain-facing balcony. Premium furnishing, modular kitchen, yoga space access.',
    price: 35000,
    city: 'Rishikesh',
    area: 'Tapovan',
    pincode: '249192',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'gym', 'parking', 'security', 'cctv'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'full',
    pet_friendly: false,
    balcony: true,
    landlord_verified: true,
    nearby_landmarks: 'Laxman Jhula 1km, Ganga Aarti Ghat 10 min walk',
    views: 567,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    landlord: { name: 'Aisha Bisht', phone: '+91 76543 21098', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha' },
    created_at: '2026-01-10',
  },
  {
    id: 'd5e6f7g8-h9i0-4j1k-2l3m-4n5o6p7q8r9s',
    title: 'Boys Hostel near Medical College',
    description: 'Clean and secure hostel for medical students. Attached bathrooms, study room, 24hr power backup.',
    price: 6000,
    city: 'Haldwani',
    area: 'Mukhani',
    pincode: '263139',
    type: 'Hostel',
    amenities: ['wifi', 'security', 'power', 'water', 'laundry'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'semi',
    pet_friendly: false,
    balcony: false,
    landlord_verified: false,
    nearby_landmarks: 'MB Post Graduate College 200m, Nainital Road 2km',
    views: 389,
    images: [
      'https://images.unsplash.com/photo-1520166012956-add9ba0835cb?w=800&q=80',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80',
    ],
    landlord: { name: 'Mohammed Ali', phone: '+91 65432 10987', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohammed' },
    created_at: '2026-01-25',
  },
  {
    id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    title: 'Spacious Room in Dharampur',
    description: 'Bright, airy room in a shared 3BHK. Great community, working professional flatmates only.',
    price: 12000,
    city: 'Dehradun',
    area: 'Dharampur',
    pincode: '248001',
    type: 'Room',
    amenities: ['wifi', 'ac', 'parking', 'security'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'semi',
    pet_friendly: true,
    balcony: true,
    landlord_verified: true,
    nearby_landmarks: 'ISBT 1km, Race Course 2km',
    views: 145,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    landlord: { name: 'Sunita Chauhan', phone: '+91 54321 09876', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sunita' },
    created_at: '2026-02-01',
  },
  {
    id: 'f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c',
    title: 'Girls PG near University',
    description: 'Safe, hygienic PG for working women. Home-cooked meals 3x daily, strict no-visitor policy, CCTV.',
    price: 9500,
    city: 'Dehradun',
    area: 'Prem Nagar',
    pincode: '248007',
    type: 'PG',
    amenities: ['wifi', 'food', 'security', 'cctv', 'laundry', 'water'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'full',
    pet_friendly: false,
    balcony: false,
    landlord_verified: true,
    nearby_landmarks: 'UPES Campus 3km, Selakui 2km',
    views: 276,
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    landlord: { name: 'Kavitha Pundir', phone: '+91 43210 98765', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavitha' },
    created_at: '2026-02-05',
  },
  {
    id: 'd0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4g',
    title: 'Premium 2BHK near Hinjewadi IT Park',
    description: 'Luxurious 2BHK with modular kitchen, covered parking, and club house access.',
    price: 28000,
    city: 'Pune',
    area: 'Hinjewadi',
    pincode: '411057',
    type: 'Flat',
    amenities: ['wifi', 'ac', 'gym', 'parking', 'security', 'cctv', 'power'],
    availability: true,
    bedrooms: 2,
    furnishing_type: 'full',
    pet_friendly: false,
    balcony: true,
    landlord_verified: true,
    nearby_landmarks: 'Infosys Campus 1km, Wipro 2km, Hinjewadi Phase 2',
    views: 498,
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    ],
    landlord: { name: 'Vikram Desai', phone: '+91 32109 87654', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram' },
    created_at: '2026-01-08',
  },
  {
    id: 'a9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d',
    title: 'Student Room near DU North Campus',
    description: 'Affordable room for Delhi University students. Attached bathroom, study table, 24hr electricity.',
    price: 7000,
    city: 'Delhi',
    area: 'Hudson Line',
    pincode: '110009',
    type: 'Room',
    amenities: ['wifi', 'security', 'power', 'water'],
    availability: true,
    bedrooms: 1,
    furnishing_type: 'semi',
    pet_friendly: false,
    balcony: false,
    landlord_verified: false,
    nearby_landmarks: 'North Campus 300m, Civil Lines Metro 1km',
    views: 203,
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
      'https://images.unsplash.com/photo-1520166012956-add9ba0835cb?w=800&q=80',
    ],
    landlord: { name: 'Anand Gupta', phone: '+91 21098 76543', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anand' },
    created_at: '2026-02-10',
  },
]

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-1',
    participantId: 'landlord-rajesh',
    participantName: 'Rajesh Negi',
    participantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    propertyId: 'e2fa5154-1506-4b47-9dc4-142f1f582d9f',
    propertyTitle: 'Premium Studio near IT Park',
    lastMessage: 'Yes, the studio is still available. Would you like to schedule a visit?',
    lastMessageTime: '2026-07-20T14:30:00Z',
    unreadCount: 2,
    messages: [
      { id: 'm1', senderId: 'dummy-user-123', text: 'Hi, is the premium studio still available?', timestamp: '2026-07-20T12:00:00Z' },
      { id: 'm2', senderId: 'landlord-rajesh', text: 'Hello! Yes, it is still available for rent.', timestamp: '2026-07-20T12:30:00Z' },
      { id: 'm3', senderId: 'dummy-user-123', text: 'Great! Can I come see it this weekend?', timestamp: '2026-07-20T13:00:00Z' },
      { id: 'm4', senderId: 'landlord-rajesh', text: 'Yes, the studio is still available. Would you like to schedule a visit?', timestamp: '2026-07-20T14:30:00Z' },
    ],
  },
  {
    id: 'conv-2',
    participantId: 'landlord-aisha',
    participantName: 'Aisha Bisht',
    participantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    propertyId: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
    propertyTitle: 'Modern 1BHK in Rishikesh',
    lastMessage: 'The rent is ₹35,000 per month including maintenance.',
    lastMessageTime: '2026-07-19T10:15:00Z',
    unreadCount: 0,
    messages: [
      { id: 'm5', senderId: 'dummy-user-123', text: 'Hi Aisha, what is the monthly rent for this apartment?', timestamp: '2026-07-19T09:00:00Z' },
      { id: 'm6', senderId: 'landlord-aisha', text: 'The rent is ₹35,000 per month including maintenance.', timestamp: '2026-07-19T10:15:00Z' },
    ],
  },
  {
    id: 'conv-3',
    participantId: 'landlord-sunita',
    participantName: 'Sunita Chauhan',
    participantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sunita',
    propertyId: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
    propertyTitle: 'Spacious Room in Dharampur',
    lastMessage: 'Yes, pet-friendly accommodation is available!',
    lastMessageTime: '2026-07-18T16:45:00Z',
    unreadCount: 1,
    messages: [
      { id: 'm7', senderId: 'dummy-user-123', text: 'Is the room pet-friendly? I have a small cat.', timestamp: '2026-07-18T16:00:00Z' },
      { id: 'm8', senderId: 'landlord-sunita', text: 'Yes, pet-friendly accommodation is available!', timestamp: '2026-07-18T16:45:00Z' },
    ],
  },
]

export const MOCK_SAVED_SEARCHES = [
  { id: 'ss-1', name: 'Flats in Dehradun', filters: { city: 'Dehradun', type: 'Flat', priceMax: 20000 }, createdAt: '2026-07-15', notifyOnMatch: true },
  { id: 'ss-2', name: 'Rooms under ₹10K', filters: { type: 'Room', priceMax: 10000 }, createdAt: '2026-07-10', notifyOnMatch: false },
]

export const CAROUSEL_SLIDES = [
  {
    id: 1,
    title: 'Find Your Perfect Stay',
    subtitle: 'Thousands of verified rooms, flats & PGs across Uttarakhand',
    cta: 'Explore Now',
    bg: 'from-brand-400 to-brand-600',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1400&q=80',
  },
  {
    id: 2,
    title: 'Students Love GOEAZY',
    subtitle: 'Budget-friendly PGs & hostels near top universities',
    cta: 'Browse PGs',
    bg: 'from-accent-400 to-accent-600',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1400&q=80',
  },
  {
    id: 3,
    title: 'Premium Flats for Professionals',
    subtitle: 'Fully furnished apartments near business districts',
    cta: 'View Flats',
    bg: 'from-purple-400 to-purple-600',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1400&q=80',
  },
]
